CREATE TABLE smsapps (
  id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(15),
  status VARCHAR(10),
  gupshup_login VARCHAR(15),
  gupshup_password VARCHAR(30)
);

CREATE TABLE masks (
  id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(12),
  status VARCHAR(10),
  smsapp_id INT NOT NULL DEFAULT -1
);

CREATE TABLE keywords (
  id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(12),
  status VARCHAR(10),
  smsapp_id INT NOT NULL DEFAULT -1
);

CREATE TABLE kvpairs (
  id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  phone BIGINT NOT NULL DEFAULT -1,
  fkey VARCHAR(20) NOT NULL,
  fvalue VARCHAR(80) NOT NULL,
  smsapp_id INT NOT NULL DEFAULT -1,
  created_at BIGINT NOT NULL DEFAULT -1,
  updated_at BIGINT NOT NULL DEFAULT -1
);
